# Created by: Adam Weinberger <adamw@FreeBSD.org>
# $FreeBSD: head/graphics/atril-lite/Makefile 407209 2016-01-25 12:31:21Z kwm $

PORTREVISION=	0
PKGNAMESUFFIX=	-lite

COMMENT=	MATE multi-format document viewer

OPTIONS_EXCLUDE=	CAJA

MASTERDIR=      ${.CURDIR}/../../graphics/atril
SLAVEPORT=      lite
DESCR=		${.CURDIR}/pkg-descr
PLIST=          ${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
